# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.8
      with:
        reports: './Queuebal.UnitTests.*/coverage/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: coveragereport
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        fail-on-error: false
        file: ./coveragereport/Cobertura.xml
    - name: Publish NuGet - Json
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Json/Queuebal.Json.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet - Json Data
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Json.Data/Queuebal.Json.Data.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet - Expressions
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Expressions/Queuebal.Expressions.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet - Conditions
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Expressions.Conditions/Queuebal.Expressions.Conditions.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet - Mutations
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Expressions.Mutations/Queuebal.Expressions.Mutations.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet - Serialization
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Serialization/Queuebal.Serialization.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet - Tools
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Queuebal.Expressions.Tools/Queuebal.Expressions.Tools.csproj
        VERSION_FILE_PATH: ./Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
