# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.8
      with:
        reports: './Queuebal.UnitTests.*/coverage/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: coveragereport
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        fail-on-error: false
        file: ./coveragereport/Cobertura.xml
    - name: Build Release
      run: dotnet build --no-restore -c Release
    - name: Publish NuGet - Json
      run: dotnet nuget push ./Queuebal.Json/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Publish NuGet - Json Data
      run: dotnet nuget push ./Queuebal.Json.Data/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Publish NuGet - Expressions
      run: dotnet nuget push ./Queuebal.Expressions/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Publish NuGet - Conditions
      run: dotnet nuget push ./Queuebal.Expressions.Conditions/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Publish NuGet - Mutations
      run: dotnet nuget push ./Queuebal.Expressions.Mutations/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Publish NuGet - Serialization
      run: dotnet nuget push ./Queuebal.Serialization/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Publish NuGet - Tools
      run: dotnet nuget push ./Queuebal.Expressions.Tools/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
